[workspace]
dependencies_update = true
changelog_update = false

[[package]]
name = "test-r-example"
release = false

[[package]]
name = "test-r-example-tokio"
release = false

[[package]]
name = "test-r-github"
release = false

[[package]]
name = "test-r"
changelog_update = true
changelog_include = ["test-r-core", "test-r-macro"]

[[package]]
name = "test-r-core"

[[package]]
name = "test-r-macro"
