[package]
name = "test-r-macro"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
test-r-core = { version = "0.1.0", path = "../test-r-core" }

heck = "0.5"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
