[package]
name = "test-r-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
test-r-core = { version = "0.1.0", path = "../test-r-core" }

heck = "0.5.0"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.67", features = ["full"] }
