[package]
name = "test-r"
version = "0.1.0"
edition = "2021"

[dependencies]
test-r-core = { version = "0.1.0", path = "../test-r-core", default-features = false }
test-r-macro = { version = "0.1.0", path = "../test-r-macros" }

ctor = "0.2.8"
tokio = { version = "1.38.0", features = ["rt-multi-thread"], optional = true }

[features]
default = ["tokio"]
tokio = ["dep:tokio", "test-r-core/tokio"]