[package]
name = "test-r-core"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
escape8259 = "0.5.3"
futures = "0.3.30"
quick-xml = "0.33.0"
tokio = { version = "1.38.0", features = ["rt-multi-thread"], optional = true }

[features]
default = ["tokio"]
tokio = ["dep:tokio"]